[application]
out_dir = "dist"

[web.app]
title = "Todo App"

[web.watcher]
watch_path = ["src", "assets"]

[web.resource]
style = ["assets/tailwind.css", "assets/main.css"]
script = []

[web.resource.dev]
script = []
